Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"

    config.vm.provider "virtualbox" do |vb|
        vb.linked_clone = true
    end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
    end

    config.vm.define "R" do |machine|
        machine.vm.hostname = "R"
        machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false
        machine.vm.network "private_network", virtualbox__intnet: "NET2", auto_config: false
    end
    
    (1..1).each do |i|
        config.vm.define "C#{i}" do |machine|
            machine.vm.hostname = "C#{i}"
            machine.vm.network "private_network", virtualbox__intnet: "NET1", auto_config: false
        end
    end

    (1..2).each do |i|
        config.vm.define "S#{i}" do |machine|
            machine.vm.hostname = "S#{i}"
            machine.vm.network "private_network", virtualbox__intnet: "NET2", auto_config: false
        end
    end
end